#!/bin/sh
websites=("youtube.com" "yahoo.com" "facebook.com" "reddit.com" "instructure.com" "stackoverflow.com" "linkedin.com" "irs.gov" "nytimes.com" "cnn.com" "salesforce.com" "okta.com" "wikipedia.org" "imgur.com" "dropbox.com" "etsy.com" "hulu.com" "quizlet.com" "homedepot.com" "netflix.com")
count=1
hour=8
#mkdir "run${hour}"
sleep 1.5
for w in "${websites[@]}"
do
    tshark -I -a duration:10 -T fields -e frame.number -e _ws.col.Time -e _ws.col.Source -e _ws.col.Destination -e _ws.col.Protocol -e frame.len -e _ws.col.Info -E header=y -E separator=, -E quote=d -E occurrence=f > "run${hour}/packet${count}.csv" & sleep 20.2 && count=$((count+1))
done