#!/bin/sh
websites=("youtube.com" "yahoo.com" "facebook.com" "reddit.com" "instructure.com" "stackoverflow.com" "linkedin.com" "irs.gov" "nytimes.com" "cnn.com" "salesforce.com" "okta.com" "wikipedia.org" "imgur.com" "dropbox.com" "etsy.com" "hulu.com" "quizlet.com" "homedepot.com")

for w in "${websites[@]}"
do
    #open -a "Google Chrome" $w
    sleep 1
    tshark -I -a duration:10  -T fields -e frame.number -e _ws.col.Time -e _ws.col.Source -e _ws.col.Destination -e _ws.col.Protocol -e frame.len -e _ws.col.Info -E header=y -E separator=, -E quote=d -E occurrence=f > test.csv 
    sleep 1
    #pkill chrome
done